/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.htlkaindorf.xmlinidatei.gui;

import at.htlkaindorf.xmlinidatei.bl.XMLIniApp;
import at.htlkaindorf.xmlinidatei.pojos.XMLWindow;
import javax.xml.parsers.ParserConfigurationException;

/**
 *
 * @author Admin
 */
public class SubDialog extends javax.swing.JDialog {

    private XMLWindow window;
    
    /**
     * Creates new form SubDialog
     */
    public SubDialog(java.awt.Frame parent, XMLWindow window) {
        super(parent, window.getName(), ModalityType.APPLICATION_MODAL);
        initComponents();
        window.setWindow(this);
        this.window = window;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        jLabel1.setText("Super awesome Dialog!");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        window.update(this);
        try {
            XMLIniApp.getInstance().updateWindow(window);
        } catch (ParserConfigurationException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
