package at.htlkaindorf.xmlinidatei.gui;

import at.htlkaindorf.xmlinidatei.bl.XMLIniApp;
import at.htlkaindorf.xmlinidatei.pojos.XMLWindow;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.xml.parsers.ParserConfigurationException;

public class SubFrame extends javax.swing.JFrame {

    private XMLWindow window;
    
    /** Creates new form SubFrame */
    public SubFrame(XMLWindow window) {
        initComponents();
        window.setWindow(this);
        this.window = window;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        Icon img = new ImageIcon(Paths.get(XMLIniApp.PATH, "nyan.gif").toString());
        JLabel label = new JLabel(img);
        this.getContentPane().add(label);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        window.update(this);
        try {
            XMLIniApp.getInstance().updateWindow(window);
        } catch (ParserConfigurationException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
