 package at.htlkaindorf.xmlinidatei.gui;

import at.htlkaindorf.xmlinidatei.beans.WindowType;
import at.htlkaindorf.xmlinidatei.bl.XMLIniApp;
import at.htlkaindorf.xmlinidatei.pojos.XMLWindow;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

public class XMLIniDateiGUI extends javax.swing.JFrame {

    private XMLWindow window;
    
    /**
     * Creates new form XMLIniDateiGUI
     */
    public XMLIniDateiGUI() {
        initComponents();
        try {
            window = XMLIniApp.getInstance().initWindow("main", WindowType.Frame);
            window.setWindow(this);
        } catch (ParserConfigurationException ex) {
            ex.printStackTrace();
            System.out.println("XML FILE PARSE EXCEPTION!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFrame = new javax.swing.JButton();
        btDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        btFrame.setText("new Frame");
        btFrame.setPreferredSize(new java.awt.Dimension(200, 50));
        btFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateFrame(evt);
            }
        });
        getContentPane().add(btFrame);

        btDialog.setText("new Dialog");
        btDialog.setPreferredSize(new java.awt.Dimension(200, 50));
        btDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCreateDialog(evt);
            }
        });
        getContentPane().add(btDialog);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        window.update(this);
        try {
            XMLIniApp.getInstance().updateWindow(window);
            XMLIniApp.getInstance().saveIniFile();
        } catch (ParserConfigurationException ex) {
            ex.printStackTrace();
        } catch (TransformerException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onWindowClosing

    private String getInput(String title) {
        String res = "";
        boolean error;
        do {
            res = JOptionPane.showInputDialog(this, "", title, JOptionPane.QUESTION_MESSAGE);
            if (res == null)
                return null;
            
            if(res.trim().length() == 0)
                error = true;
            else
                error = false;
        }while(error);
        
        return res;
    }
    
    private void onCreateFrame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateFrame
        String name = getInput("Create Frame");
        if(name == null) return;
        
        try {
            new SubFrame(XMLIniApp.getInstance().initWindow(name, WindowType.Frame)).setVisible(true);
        } catch (ParserConfigurationException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onCreateFrame

    private void onCreateDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCreateDialog
        String name = getInput("Create Dialog");
        if(name == null) return;
        
        try {
            new SubDialog(this, XMLIniApp.getInstance().initWindow(name, WindowType.Dialog)).setVisible(true);
        } catch (ParserConfigurationException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_onCreateDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XMLIniDateiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XMLIniDateiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XMLIniDateiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XMLIniDateiGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XMLIniDateiGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDialog;
    private javax.swing.JButton btFrame;
    // End of variables declaration//GEN-END:variables
}
